In [1]:
import cv2
import glob
import numpy as np
 
def calibrate_camera(images_folder):
    images_names = sorted(glob.glob(images_folder))
    
    images = []
    for imname in images_names:
        im = cv2.imread(imname, 1)
        images.append(im)
 
    #criteria used by checkerboard pattern detector.
    #Change this if the code can't find the checkerboard
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
    rows = 6 #number of checkerboard rows.
    columns = 8 #number of checkerboard columns.
    world_scaling = 25. # real world square size.
 
    #coordinates of squares in the checkerboard world space
    objp = np.zeros((rows*columns,3), np.float32)
    objp[:,:2] = np.mgrid[0:rows,0:columns].T.reshape(-1,2)
    objp = world_scaling* objp

    #frame dimensions. Frames should be the same size.
    width = images[0].shape[1]
    height = images[0].shape[0]
 
    #Pixel coordinates of checkerboards
    imgpoints = [] # 2d points in image plane.
 
    #coordinates of the checkerboard in checkerboard world space.
    objpoints = [] # 3d point in real world space
    i=0
    get = []
    for frame in images:
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        
        flags = (cv2.CALIB_CB_ADAPTIVE_THRESH  
        + cv2.CALIB_CB_FAST_CHECK  
        + cv2.CALIB_CB_NORMALIZE_IMAGE)
 
        #find the checkerboard
        ret, corners = cv2.findChessboardCorners(gray, (rows, columns), flags)
 
        if ret == True:
            get.append(images_names[i])
            #Convolution size used to improve corner detection. Don't make this too large.
            conv_size = (11, 11)
 
            #opencv can attempt to improve the checkerboard coordinates
            corners = cv2.cornerSubPix(gray, corners, conv_size, (-1, -1), criteria)
            cv2.drawChessboardCorners(frame, (rows,columns), corners, ret)
            # cv2.imshow('img', frame)
            # cv2.waitKey(0)
 
            objpoints.append(objp)
            imgpoints.append(corners)
        i += 1
 
    # cv2.destroyAllWindows()
 
    # ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, (width, height), None, None)
    print('detected:')
    
    # print('rmse:', ret)
    # print('camera matrix:\n', mtx)
    # print('distortion coeffs:', dist)
    # print('Rs:\n', rvecs)
    # print('Ts:\n', tvecs)
    
    # mean_error = 0
    # for i in range(len(objpoints)):
    #     imgpoints2, _ = cv2.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
    #     error = cv2.norm(imgpoints[i], imgpoints2, cv2.NORM_L2)/len(imgpoints2)
    #     mean_error += error
    # print( "total error: {}".format(mean_error/len(objpoints)) )
 
    # return mtx, dist
    yes =  cv2.calibrateCameraExtended(
        objpoints, 
        imgpoints, 
        (width, height), 
        None, 
        None,
        flags=cv2.CALIB_RATIONAL_MODEL
        )
    e = 0
    for b in get:
        print(b,":",yes[-1][e])
        e +=1
        
    return yes
 


In [2]:
# mtx, dist = calibrate_camera(images_folder = './data/1/*')
yes = calibrate_camera(images_folder = './data/1/*')
mtx1,dist1 = yes[1],yes[2]
print("RMSE :", yes[0])
print("Camera Matrix", mtx1)
print("Distortion Matrix", dist1)

detected:
./data/1\IMG_20230428_135714.jpg : [0.48455633]
./data/1\IMG_20230428_135721.jpg : [0.48215871]
./data/1\IMG_20230428_135729.jpg : [0.42536503]
./data/1\IMG_20230428_135741.jpg : [0.42054934]
./data/1\IMG_20230428_135751.jpg : [0.71331502]
./data/1\IMG_20230428_135756.jpg : [0.64869389]
./data/1\IMG_20230428_135811.jpg : [0.73579643]
./data/1\IMG_20230428_135817.jpg : [1.05512058]
./data/1\IMG_20230428_135834.jpg : [0.77803172]
./data/1\IMG_20230428_135844.jpg : [0.9150566]
./data/1\IMG_20230428_135910.jpg : [0.46453663]
./data/1\IMG_20230428_135926.jpg : [0.74599145]
./data/1\IMG_20230428_135932.jpg : [0.53898941]
./data/1\IMG_20230428_135940.jpg : [0.60164371]
./data/1\IMG_20230428_135946.jpg : [0.52282149]
./data/1\IMG_20230428_135952.jpg : [0.67805107]
./data/1\IMG_20230428_140005.jpg : [0.42119644]
./data/1\IMG_20230428_140017.jpg : [1.23081497]
./data/1\IMG_20230428_140034.jpg : [1.41255024]
./data/1\IMG_20230428_140042.jpg : [1.14619066]
./data/1\IMG_20230428_140048.jp

In [3]:
yes = calibrate_camera(images_folder = './data/2/*')
mtx2,dist2 = yes[1],yes[2]
print("RMSE :", yes[0])
print("Camera Matrix", mtx2)
print("Distortion Matrix", dist2)

detected:
./data/2\IMG_20230428_142714.jpg : [0.32765495]
./data/2\IMG_20230428_142723.jpg : [0.56440896]
./data/2\IMG_20230428_142732.jpg : [0.32519452]
./data/2\IMG_20230428_142741.jpg : [0.40139977]
./data/2\IMG_20230428_142750.jpg : [0.44301859]
./data/2\IMG_20230428_142756.jpg : [0.51034616]
./data/2\IMG_20230428_142803.jpg : [0.59205592]
./data/2\IMG_20230428_142812.jpg : [0.70657234]
./data/2\IMG_20230428_142824.jpg : [0.5246163]
./data/2\IMG_20230428_142832.jpg : [1.45674205]
./data/2\IMG_20230428_142906.jpg : [0.95652365]
./data/2\IMG_20230428_142919.jpg : [0.7202039]
./data/2\IMG_20230428_142934.jpg : [0.9439368]
./data/2\IMG_20230428_143005.jpg : [0.66361479]
./data/2\IMG_20230428_143056.jpg : [1.09728125]
./data/2\IMG_20230428_143100.jpg : [0.95002009]
./data/2\IMG_20230428_143104.jpg : [1.28285877]
RMSE : 0.8012462667281911
Camera Matrix [[1.44756078e+03 0.00000000e+00 9.62301197e+02]
 [0.00000000e+00 1.45504214e+03 5.41752772e+02]
 [0.00000000e+00 0.00000000e+00 1.0000000

In [4]:
# images_names = sorted(glob.glob('./data/2/*'))
# images = []
# for imname in images_names:
#     im = cv2.imread(imname, 1)

#     height, width, channels = im.shape
#     newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (width,height), 1, (width,height))
#     dst = cv2.undistort(im, mtx, dist, None, newcameramtx)
#     # # crop the image
#     # x, y, w, h = roi
#     # dst = dst[y:y+h, x:x+w]
    
#     diff = np.concatenate((im, dst), axis=1)
#     cv2.imshow('img', diff)
#     cv2.waitKey(0)
# cv2.destroyAllWindows()

In [29]:
def stereo_calibrate(mtx1, dist1, mtx2, dist2, folder1, folder2):
    #read the synched frames
    c1_images_names = sorted(glob.glob(folder1))
    c2_images_names = sorted(glob.glob(folder2))
 
    c1_images = []
    c2_images = []
    for im1, im2 in zip(c1_images_names, c2_images_names):
        _im = cv2.imread(im1, 1)
        c1_images.append(_im)
 
        _im = cv2.imread(im2, 1)
        c2_images.append(_im)
 
  
    #change this if stereo calibration not good.
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.0001)
 
    rows = 6 #number of checkerboard rows.
    columns = 8 #number of checkerboard columns.
    world_scaling = 25. #change this to the real world square size. Or not.
 
    #coordinates of squares in the checkerboard world space
    objp = np.zeros((rows*columns,3), np.float32)
    objp[:,:2] = np.mgrid[0:rows,0:columns].T.reshape(-1,2)
    objp = world_scaling* objp
 
    #frame dimensions. Frames should be the same size.
    width = c1_images[0].shape[1]
    height = c1_images[0].shape[0]
 
    #Pixel coordinates of checkerboards
    imgpoints_left = [] # 2d points in image plane.
    imgpoints_right = []
 
    #coordinates of the checkerboard in checkerboard world space.
    objpoints = [] # 3d point in real world space
    
    get = []
    i = 0
    
    for frame1, frame2 in zip(c1_images, c2_images):
        gray1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
        gray2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)
        
        detectChessboardflags = (cv2.CALIB_CB_ADAPTIVE_THRESH  
        + cv2.CALIB_CB_FAST_CHECK  
        + cv2.CALIB_CB_NORMALIZE_IMAGE)
 
        c_ret1, corners1 = cv2.findChessboardCorners(gray1, (rows, columns), detectChessboardflags)
        c_ret2, corners2 = cv2.findChessboardCorners(gray2, (rows, columns), detectChessboardflags)
 
        if c_ret1 == True and c_ret2 == True:
            get.append([c1_images_names[i],c2_images_names[i]])
            corners1 = cv2.cornerSubPix(gray1, corners1, (11, 11), (-1, -1), criteria)
            corners2 = cv2.cornerSubPix(gray2, corners2, (11, 11), (-1, -1), criteria)
 
            cv2.drawChessboardCorners(frame1, (rows, columns), corners1, c_ret1)
            
 
            cv2.drawChessboardCorners(frame2, (rows, columns), corners2, c_ret2)
            
            
            Sres = np.concatenate((frame1, frame2), axis=1)
            cv2.namedWindow('Sres',cv2.WND_PROP_FULLSCREEN)
            cv2.setWindowProperty('Sres', cv2.WND_PROP_FULLSCREEN,cv2.WINDOW_FULLSCREEN)
            cv2.imshow('Sres', Sres)
            cv2.waitKey(0)
            
 
            objpoints.append(objp)
            imgpoints_left.append(corners1)
            imgpoints_right.append(corners2)

        i += 1
            
    
    cv2.destroyAllWindows()
    stereocalibration_flags = cv2.CALIB_FIX_INTRINSIC + cv2.CALIB_RATIONAL_MODEL
    ret, CM1, dist1, CM2, dist2, R, T, E, F = cv2.stereoCalibrate(objpoints, imgpoints_left, imgpoints_right, mtx1, dist1,
                                                                 mtx2, dist2, (width, height), criteria = criteria, flags = stereocalibration_flags)
    
    #print(viewErrors)
    print(ret)
    print("Detected :")
    for k in range(len(get)):
        print("1st Camera :",get[k][0])
        print("2nd Camera :",get[k][1])
        print()
        
    
    return R, T
    

In [30]:
stereo_calibrate(mtx1, dist1, mtx2, dist2, './data/3.1/*','./data/3.2/*')


45.34367575289382
Detected :
1st Camera : ./data/3.1\IMG_20230428_144843.jpg
2nd Camera : ./data/3.2\IMG_20230428_144841.jpg

1st Camera : ./data/3.1\IMG_20230428_145049.jpg
2nd Camera : ./data/3.2\IMG_20230428_145047.jpg

1st Camera : ./data/3.1\IMG_20230428_145112.jpg
2nd Camera : ./data/3.2\IMG_20230428_145110.jpg

1st Camera : ./data/3.1\IMG_20230428_145138.jpg
2nd Camera : ./data/3.2\IMG_20230428_145136.jpg

1st Camera : ./data/3.1\IMG_20230428_145156.jpg
2nd Camera : ./data/3.2\IMG_20230428_145154.jpg

1st Camera : ./data/3.1\IMG_20230428_145326.jpg
2nd Camera : ./data/3.2\IMG_20230428_145325.jpg

1st Camera : ./data/3.1\IMG_20230428_145349.jpg
2nd Camera : ./data/3.2\IMG_20230428_145347.jpg

1st Camera : ./data/3.1\IMG_20230428_145426.jpg
2nd Camera : ./data/3.2\IMG_20230428_145424.jpg

1st Camera : ./data/3.1\IMG_20230428_145442.jpg
2nd Camera : ./data/3.2\IMG_20230428_145440.jpg

1st Camera : ./data/3.1\IMG_20230428_145512.jpg
2nd Camera : ./data/3.2\IMG_20230428_145510.jpg

1

(array([[-0.11910047, -0.10612934,  0.98719382],
        [-0.0207616 ,  0.99431964,  0.10439062],
        [-0.99266512, -0.00806275, -0.12062735]]),
 array([[-1555.12463272],
        [ -112.28519719],
        [ 2088.46391789]]))